<?php

namespace Proxies\__CG__\DirectoryPlatform\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \DirectoryPlatform\AppBundle\Entity\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'status', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'user', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'items', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'gateway', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'currency', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'price', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'name', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'regNo', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'vatNo', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'country', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'county', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'city', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'street', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'postalCode', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'created', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'modified'];
        }

        return ['__isInitialized__', 'id', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'status', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'user', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'items', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'gateway', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'currency', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'price', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'name', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'regNo', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'vatNo', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'country', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'county', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'city', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'street', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'postalCode', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'created', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Order' . "\0" . 'modified'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function onPrePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', []);

        return parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', []);

        return parent::onPreUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', []);

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCode($postalCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCode', [$postalCode]);

        return parent::setPostalCode($postalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet', []);

        return parent::getStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet($street)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet', [$street]);

        return parent::setStreet($street);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCounty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCounty', []);

        return parent::getCounty();
    }

    /**
     * {@inheritDoc}
     */
    public function setCounty($county)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCounty', [$county]);

        return parent::setCounty($county);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryName', []);

        return parent::getCountryName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getVatNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVatNo', []);

        return parent::getVatNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setVatNo($vatNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVatNo', [$vatNo]);

        return parent::setVatNo($vatNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegNo', []);

        return parent::getRegNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegNo($regNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegNo', [$regNo]);

        return parent::setRegNo($regNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', [$currency]);

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getGateway()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGateway', []);

        return parent::getGateway();
    }

    /**
     * {@inheritDoc}
     */
    public function setGateway($gateway)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGateway', [$gateway]);

        return parent::setGateway($gateway);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getDueDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDueDate', []);

        return parent::getDueDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItems', []);

        return parent::getItems();
    }

    /**
     * {@inheritDoc}
     */
    public function setItems($items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItems', [$items]);

        return parent::setItems($items);
    }

}
