<?php

namespace Proxies\__CG__\DirectoryPlatform\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \DirectoryPlatform\AppBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'productName', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'sku', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'user', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'category', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'enabled', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'inventory', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'percentageThc', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'percentageThca', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'percentageCbd', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'percentageCba', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'percentageCbn', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'priceGram', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'price2Gram', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'price35Gram', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'price4Gram', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'price7Gram', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'price14Gram', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'price28Gram', 'slug', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'created', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'modified'];
        }

        return ['__isInitialized__', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'productName', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'sku', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'user', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'category', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'enabled', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'inventory', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'percentageThc', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'percentageThca', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'percentageCbd', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'percentageCba', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'percentageCbn', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'priceGram', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'price2Gram', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'price35Gram', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'price4Gram', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'price7Gram', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'price14Gram', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'price28Gram', 'slug', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'created', '' . "\0" . 'DirectoryPlatform\\AppBundle\\Entity\\Product' . "\0" . 'modified'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', []);

        return parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', []);

        return parent::onPreUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getVendor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVendor', []);

        return parent::getVendor();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductName($productName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductName', [$productName]);

        return parent::setProductName($productName);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductName', []);

        return parent::getProductName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSku($sku)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSku', [$sku]);

        return parent::setSku($sku);
    }

    /**
     * {@inheritDoc}
     */
    public function getSku()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSku', []);

        return parent::getSku();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', []);

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setInventory($inventory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInventory', [$inventory]);

        return parent::setInventory($inventory);
    }

    /**
     * {@inheritDoc}
     */
    public function getInventory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInventory', []);

        return parent::getInventory();
    }

    /**
     * {@inheritDoc}
     */
    public function setPercentageThc($percentageThc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercentageThc', [$percentageThc]);

        return parent::setPercentageThc($percentageThc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPercentageThc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercentageThc', []);

        return parent::getPercentageThc();
    }

    /**
     * {@inheritDoc}
     */
    public function setPercentageThca($percentageThca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercentageThca', [$percentageThca]);

        return parent::setPercentageThca($percentageThca);
    }

    /**
     * {@inheritDoc}
     */
    public function getPercentageThca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercentageThca', []);

        return parent::getPercentageThca();
    }

    /**
     * {@inheritDoc}
     */
    public function setPercentageCbd($percentageCbd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercentageCbd', [$percentageCbd]);

        return parent::setPercentageCbd($percentageCbd);
    }

    /**
     * {@inheritDoc}
     */
    public function getPercentageCbd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercentageCbd', []);

        return parent::getPercentageCbd();
    }

    /**
     * {@inheritDoc}
     */
    public function setPercentageCba($percentageCba)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercentageCba', [$percentageCba]);

        return parent::setPercentageCba($percentageCba);
    }

    /**
     * {@inheritDoc}
     */
    public function getPercentageCba()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercentageCba', []);

        return parent::getPercentageCba();
    }

    /**
     * {@inheritDoc}
     */
    public function setPercentageCbn($percentageCbn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercentageCbn', [$percentageCbn]);

        return parent::setPercentageCbn($percentageCbn);
    }

    /**
     * {@inheritDoc}
     */
    public function getPercentageCbn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercentageCbn', []);

        return parent::getPercentageCbn();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceGram($priceGram)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceGram', [$priceGram]);

        return parent::setPriceGram($priceGram);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceGram()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceGram', []);

        return parent::getPriceGram();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice2Gram($price2Gram)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice2Gram', [$price2Gram]);

        return parent::setPrice2Gram($price2Gram);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice2Gram()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice2Gram', []);

        return parent::getPrice2Gram();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice35Gram($price35Gram)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice35Gram', [$price35Gram]);

        return parent::setPrice35Gram($price35Gram);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice35Gram()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice35Gram', []);

        return parent::getPrice35Gram();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice4Gram($price4Gram)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice4Gram', [$price4Gram]);

        return parent::setPrice4Gram($price4Gram);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice4Gram()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice4Gram', []);

        return parent::getPrice4Gram();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice7Gram($price7Gram)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice7Gram', [$price7Gram]);

        return parent::setPrice7Gram($price7Gram);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice7Gram()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice7Gram', []);

        return parent::getPrice7Gram();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice14Gram($price14Gram)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice14Gram', [$price14Gram]);

        return parent::setPrice14Gram($price14Gram);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice14Gram()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice14Gram', []);

        return parent::getPrice14Gram();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice28Gram($price28Gram)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice28Gram', [$price28Gram]);

        return parent::setPrice28Gram($price28Gram);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice28Gram()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice28Gram', []);

        return parent::getPrice28Gram();
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

}
